// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `InterfaceMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __InterfaceMP3_h__
#define __InterfaceMP3_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace ArchDistrib
{

class Tag;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::Tag>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ArchDistrib::Tag*);

class Song;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::Song>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ArchDistrib::Song*);

class SongModel;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::SongModel>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ArchDistrib::SongModel*);

class InterfaceMP3;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::InterfaceMP3>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ArchDistrib::InterfaceMP3*);

}

}

namespace ArchDistrib
{

class Tag;
::Ice::Object* upCast(::ArchDistrib::Tag*);
typedef ::IceInternal::Handle< ::ArchDistrib::Tag> TagPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::Tag> TagPrx;
void __patch(TagPtr&, const ::Ice::ObjectPtr&);

class Song;
::Ice::Object* upCast(::ArchDistrib::Song*);
typedef ::IceInternal::Handle< ::ArchDistrib::Song> SongPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::Song> SongPrx;
void __patch(SongPtr&, const ::Ice::ObjectPtr&);

class SongModel;
::Ice::Object* upCast(::ArchDistrib::SongModel*);
typedef ::IceInternal::Handle< ::ArchDistrib::SongModel> SongModelPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::SongModel> SongModelPrx;
void __patch(SongModelPtr&, const ::Ice::ObjectPtr&);

class InterfaceMP3;
::Ice::Object* upCast(::ArchDistrib::InterfaceMP3*);
typedef ::IceInternal::Handle< ::ArchDistrib::InterfaceMP3> InterfaceMP3Ptr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::InterfaceMP3> InterfaceMP3Prx;
void __patch(InterfaceMP3Ptr&, const ::Ice::ObjectPtr&);

}

namespace ArchDistrib
{

typedef ::std::vector< ::Ice::Float> DataSeq;

typedef ::std::vector< ::ArchDistrib::TagPtr> TagSeq;

}

namespace ArchDistrib
{

class Callback_InterfaceMP3_printString_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_InterfaceMP3_printString_Base> Callback_InterfaceMP3_printStringPtr;

}

namespace IceProxy
{

namespace ArchDistrib
{

class Tag : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<Tag> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_secure(bool __secure) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_twoway() const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_oneway() const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_batchOneway() const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_datagram() const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_batchDatagram() const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_compress(bool __compress) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Tag> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Tag*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class Song : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<Song> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_secure(bool __secure) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_twoway() const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_oneway() const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_batchOneway() const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_datagram() const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_batchDatagram() const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_compress(bool __compress) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Song> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Song*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class SongModel : virtual public ::IceProxy::ArchDistrib::Song
{
public:
    
    ::IceInternal::ProxyHandle<SongModel> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_secure(bool __secure) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_twoway() const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_oneway() const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_batchOneway() const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_datagram() const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_batchDatagram() const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_compress(bool __compress) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_timeout(int __timeout) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SongModel> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<SongModel*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class InterfaceMP3 : virtual public ::IceProxy::Ice::Object
{
public:

    void printString(const ::std::string& __p_s)
    {
        printString(__p_s, 0);
    }
    void printString(const ::std::string& __p_s, const ::Ice::Context& __ctx)
    {
        printString(__p_s, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_printString(const ::std::string& __p_s, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_printString(__p_s, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_printString(const ::std::string& __p_s, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_printString(__p_s, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_printString(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_printString(__p_s, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_printString(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_printString(__p_s, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s)
    {
        return begin_printString(__p_s, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s, const ::Ice::Context& __ctx)
    {
        return begin_printString(__p_s, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printString(__p_s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printString(__p_s, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s, const ::ArchDistrib::Callback_InterfaceMP3_printStringPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printString(__p_s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printString(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::ArchDistrib::Callback_InterfaceMP3_printStringPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printString(__p_s, &__ctx, __del, __cookie);
    }

    void end_printString(const ::Ice::AsyncResultPtr&);
    
private:

    void printString(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_printString(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_secure(bool __secure) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_twoway() const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_oneway() const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_batchOneway() const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_datagram() const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_batchDatagram() const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_compress(bool __compress) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_timeout(int __timeout) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<InterfaceMP3> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<InterfaceMP3*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace ArchDistrib
{

class Tag : virtual public ::Ice::Object
{
public:

    typedef TagPrx ProxyType;
    typedef TagPtr PointerType;

    Tag()
    {
    }

    explicit Tag(const ::std::string& __ice_name) :
        name(__ice_name)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();


    static ::Ice::ObjectFactoryPtr ice_factory();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;

public:

    ::std::string name;
protected:

    virtual ~Tag() {}

friend class Tag__staticInit;
};
#if !defined(_MSC_VER) || (_MSC_VER < 1900)
//
// COMPILERFIX: Visual Studio 2015 update 1 fails to access
// the proected destructor from a friend class.
//

class Tag__staticInit
{
public:

    ::ArchDistrib::Tag _init;
};

static Tag__staticInit _Tag_init;
#else
static auto _Tag_init = ::ArchDistrib::Tag::ice_factory;
#endif

inline bool operator==(const Tag& l, const Tag& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Tag& l, const Tag& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class Song : virtual public ::Ice::Object, public ::IceInternal::GCObject
{
public:

    typedef SongPrx ProxyType;
    typedef SongPtr PointerType;

    Song()
    {
    }

    Song(const ::std::string& __ice_name, const ::std::string& __ice_artist, const ::ArchDistrib::DataSeq& __ice_data, const ::ArchDistrib::TagSeq& __ice_tags) :
        name(__ice_name),
        artist(__ice_artist),
        data(__ice_data),
        tags(__ice_tags)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void __gcVisitMembers(::IceInternal::GCVisitor&);

    static ::Ice::ObjectFactoryPtr ice_factory();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;

public:

    ::std::string name;

    ::std::string artist;

    ::ArchDistrib::DataSeq data;

    ::ArchDistrib::TagSeq tags;
protected:

    virtual ~Song() {}
};

inline bool operator==(const Song& l, const Song& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Song& l, const Song& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class SongModel : public ::ArchDistrib::Song
{
public:

    typedef SongModelPrx ProxyType;
    typedef SongModelPtr PointerType;

    SongModel()
    {
    }

    SongModel(const ::std::string& __ice_name, const ::std::string& __ice_artist, const ::ArchDistrib::DataSeq& __ice_data, const ::ArchDistrib::TagSeq& __ice_tags, const ::std::string& __ice_path) :
        ::ArchDistrib::Song(__ice_name, __ice_artist, __ice_data, __ice_tags),
        path(__ice_path)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void __gcVisitMembers(::IceInternal::GCVisitor&);

    static ::Ice::ObjectFactoryPtr ice_factory();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::ArchDistrib::Song::__writeImpl;
    using ::ArchDistrib::Song::__readImpl;

public:

    ::std::string path;
protected:

    virtual ~SongModel() {}
};

inline bool operator==(const SongModel& l, const SongModel& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const SongModel& l, const SongModel& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class InterfaceMP3 : virtual public ::Ice::Object
{
public:

    typedef InterfaceMP3Prx ProxyType;
    typedef InterfaceMP3Ptr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void printString(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___printString(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const InterfaceMP3& l, const InterfaceMP3& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const InterfaceMP3& l, const InterfaceMP3& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace ArchDistrib
{

template<class T>
class CallbackNC_InterfaceMP3_printString : public Callback_InterfaceMP3_printString_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_InterfaceMP3_printString(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InterfaceMP3_printString<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InterfaceMP3_printString<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InterfaceMP3_printString<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InterfaceMP3_printString<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_InterfaceMP3_printString : public Callback_InterfaceMP3_printString_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_InterfaceMP3_printString(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InterfaceMP3_printString<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InterfaceMP3_printString<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InterfaceMP3_printString<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_InterfaceMP3_printStringPtr
newCallback_InterfaceMP3_printString(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InterfaceMP3_printString<T, CT>(instance, 0, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
