# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `InterfaceMP3.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module ArchDistrib
_M_ArchDistrib = Ice.openModule('ArchDistrib')
__name__ = 'ArchDistrib'

if 'Tag' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib.Tag = Ice.createTempClass()
    class Tag(Ice.Object):
        def __init__(self, name=''):
            self.name = name

        def ice_ids(self, current=None):
            return ('::ArchDistrib::Tag', '::Ice::Object')

        def ice_id(self, current=None):
            return '::ArchDistrib::Tag'

        def ice_staticId():
            return '::ArchDistrib::Tag'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_ArchDistrib._t_Tag)

        __repr__ = __str__

    _M_ArchDistrib.TagPrx = Ice.createTempClass()
    class TagPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_ArchDistrib.TagPrx.ice_checkedCast(proxy, '::ArchDistrib::Tag', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_ArchDistrib.TagPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::ArchDistrib::Tag'
        ice_staticId = staticmethod(ice_staticId)

    _M_ArchDistrib._t_TagPrx = IcePy.defineProxy('::ArchDistrib::Tag', TagPrx)

    _M_ArchDistrib._t_Tag = IcePy.defineClass('::ArchDistrib::Tag', Tag, -1, (), False, False, None, (), (('name', (), IcePy._t_string, False, 0),))
    Tag._ice_type = _M_ArchDistrib._t_Tag

    _M_ArchDistrib.Tag = Tag
    del Tag

    _M_ArchDistrib.TagPrx = TagPrx
    del TagPrx

if '_t_DataSeq' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib._t_DataSeq = IcePy.defineSequence('::ArchDistrib::DataSeq', (), IcePy._t_float)

if '_t_TagSeq' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib._t_TagSeq = IcePy.defineSequence('::ArchDistrib::TagSeq', (), _M_ArchDistrib._t_Tag)

if 'Song' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib.Song = Ice.createTempClass()
    class Song(Ice.Object):
        def __init__(self, name='', artist='', data=None, tags=None):
            self.name = name
            self.artist = artist
            self.data = data
            self.tags = tags

        def ice_ids(self, current=None):
            return ('::ArchDistrib::Song', '::Ice::Object')

        def ice_id(self, current=None):
            return '::ArchDistrib::Song'

        def ice_staticId():
            return '::ArchDistrib::Song'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_ArchDistrib._t_Song)

        __repr__ = __str__

    _M_ArchDistrib.SongPrx = Ice.createTempClass()
    class SongPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_ArchDistrib.SongPrx.ice_checkedCast(proxy, '::ArchDistrib::Song', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_ArchDistrib.SongPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::ArchDistrib::Song'
        ice_staticId = staticmethod(ice_staticId)

    _M_ArchDistrib._t_SongPrx = IcePy.defineProxy('::ArchDistrib::Song', SongPrx)

    _M_ArchDistrib._t_Song = IcePy.declareClass('::ArchDistrib::Song')

    _M_ArchDistrib._t_Song = IcePy.defineClass('::ArchDistrib::Song', Song, -1, (), False, False, None, (), (
        ('name', (), IcePy._t_string, False, 0),
        ('artist', (), IcePy._t_string, False, 0),
        ('data', (), _M_ArchDistrib._t_DataSeq, False, 0),
        ('tags', (), _M_ArchDistrib._t_TagSeq, False, 0)
    ))
    Song._ice_type = _M_ArchDistrib._t_Song

    _M_ArchDistrib.Song = Song
    del Song

    _M_ArchDistrib.SongPrx = SongPrx
    del SongPrx

if 'SongModel' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib.SongModel = Ice.createTempClass()
    class SongModel(_M_ArchDistrib.Song):
        def __init__(self, name='', artist='', data=None, tags=None, path=''):
            _M_ArchDistrib.Song.__init__(self, name, artist, data, tags)
            self.path = path

        def ice_ids(self, current=None):
            return ('::ArchDistrib::Song', '::ArchDistrib::SongModel', '::Ice::Object')

        def ice_id(self, current=None):
            return '::ArchDistrib::SongModel'

        def ice_staticId():
            return '::ArchDistrib::SongModel'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_ArchDistrib._t_SongModel)

        __repr__ = __str__

    _M_ArchDistrib.SongModelPrx = Ice.createTempClass()
    class SongModelPrx(_M_ArchDistrib.SongPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_ArchDistrib.SongModelPrx.ice_checkedCast(proxy, '::ArchDistrib::SongModel', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_ArchDistrib.SongModelPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::ArchDistrib::SongModel'
        ice_staticId = staticmethod(ice_staticId)

    _M_ArchDistrib._t_SongModelPrx = IcePy.defineProxy('::ArchDistrib::SongModel', SongModelPrx)

    _M_ArchDistrib._t_SongModel = IcePy.declareClass('::ArchDistrib::SongModel')

    _M_ArchDistrib._t_SongModel = IcePy.defineClass('::ArchDistrib::SongModel', SongModel, -1, (), False, False, _M_ArchDistrib._t_Song, (), (('path', (), IcePy._t_string, False, 0),))
    SongModel._ice_type = _M_ArchDistrib._t_SongModel

    _M_ArchDistrib.SongModel = SongModel
    del SongModel

    _M_ArchDistrib.SongModelPrx = SongModelPrx
    del SongModelPrx

if 'InterfaceMP3' not in _M_ArchDistrib.__dict__:
    _M_ArchDistrib.InterfaceMP3 = Ice.createTempClass()
    class InterfaceMP3(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_ArchDistrib.InterfaceMP3:
                raise RuntimeError('ArchDistrib.InterfaceMP3 is an abstract class')

        def ice_ids(self, current=None):
            return ('::ArchDistrib::InterfaceMP3', '::Ice::Object')

        def ice_id(self, current=None):
            return '::ArchDistrib::InterfaceMP3'

        def ice_staticId():
            return '::ArchDistrib::InterfaceMP3'
        ice_staticId = staticmethod(ice_staticId)

        def printString(self, s, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_ArchDistrib._t_InterfaceMP3)

        __repr__ = __str__

    _M_ArchDistrib.InterfaceMP3Prx = Ice.createTempClass()
    class InterfaceMP3Prx(Ice.ObjectPrx):

        def printString(self, s, _ctx=None):
            return _M_ArchDistrib.InterfaceMP3._op_printString.invoke(self, ((s, ), _ctx))

        def begin_printString(self, s, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_ArchDistrib.InterfaceMP3._op_printString.begin(self, ((s, ), _response, _ex, _sent, _ctx))

        def end_printString(self, _r):
            return _M_ArchDistrib.InterfaceMP3._op_printString.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_ArchDistrib.InterfaceMP3Prx.ice_checkedCast(proxy, '::ArchDistrib::InterfaceMP3', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_ArchDistrib.InterfaceMP3Prx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::ArchDistrib::InterfaceMP3'
        ice_staticId = staticmethod(ice_staticId)

    _M_ArchDistrib._t_InterfaceMP3Prx = IcePy.defineProxy('::ArchDistrib::InterfaceMP3', InterfaceMP3Prx)

    _M_ArchDistrib._t_InterfaceMP3 = IcePy.defineClass('::ArchDistrib::InterfaceMP3', InterfaceMP3, -1, (), True, False, None, (), ())
    InterfaceMP3._ice_type = _M_ArchDistrib._t_InterfaceMP3

    InterfaceMP3._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())

    _M_ArchDistrib.InterfaceMP3 = InterfaceMP3
    del InterfaceMP3

    _M_ArchDistrib.InterfaceMP3Prx = InterfaceMP3Prx
    del InterfaceMP3Prx

# End of module ArchDistrib
