// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `InterfaceMP3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <InterfaceMP3.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __ArchDistrib__InterfaceMP3__printString_name = "printString";

}
::IceProxy::Ice::Object* ::IceProxy::ArchDistrib::upCast(::IceProxy::ArchDistrib::InterfaceMP3* p) { return p; }

void
::IceProxy::ArchDistrib::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::ArchDistrib::InterfaceMP3>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ArchDistrib::InterfaceMP3;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::ArchDistrib::InterfaceMP3::printString(const ::std::string& s, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __ArchDistrib__InterfaceMP3__printString_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::ArchDistrib::InterfaceMP3* __del = dynamic_cast< ::IceDelegate::ArchDistrib::InterfaceMP3*>(__delBase.get());
            __del->printString(s, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ArchDistrib::InterfaceMP3::begin_printString(const ::std::string& s, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ArchDistrib__InterfaceMP3__printString_name, __del, __cookie);
    try
    {
        __result->__prepare(__ArchDistrib__InterfaceMP3__printString_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(s);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ArchDistrib::InterfaceMP3::end_printString(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ArchDistrib__InterfaceMP3__printString_name);
}

const ::std::string&
IceProxy::ArchDistrib::InterfaceMP3::ice_staticId()
{
    return ::ArchDistrib::InterfaceMP3::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ArchDistrib::InterfaceMP3::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ArchDistrib::InterfaceMP3);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ArchDistrib::InterfaceMP3::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ArchDistrib::InterfaceMP3);
}

::IceProxy::Ice::Object*
IceProxy::ArchDistrib::InterfaceMP3::__newInstance() const
{
    return new InterfaceMP3;
}

void
IceDelegateM::ArchDistrib::InterfaceMP3::printString(const ::std::string& s, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ArchDistrib__InterfaceMP3__printString_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(s);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::ArchDistrib::InterfaceMP3::printString(const ::std::string& s, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_s, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_s(__p_s)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ArchDistrib::InterfaceMP3* servant = dynamic_cast< ::ArchDistrib::InterfaceMP3*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->printString(_m_s, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_s;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __ArchDistrib__InterfaceMP3__printString_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(s, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* ArchDistrib::upCast(::ArchDistrib::InterfaceMP3* p) { return p; }

namespace
{
const ::std::string __ArchDistrib__InterfaceMP3_ids[2] =
{
    "::ArchDistrib::InterfaceMP3",
    "::Ice::Object"
};

}

bool
ArchDistrib::InterfaceMP3::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ArchDistrib__InterfaceMP3_ids, __ArchDistrib__InterfaceMP3_ids + 2, _s);
}

::std::vector< ::std::string>
ArchDistrib::InterfaceMP3::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ArchDistrib__InterfaceMP3_ids[0], &__ArchDistrib__InterfaceMP3_ids[2]);
}

const ::std::string&
ArchDistrib::InterfaceMP3::ice_id(const ::Ice::Current&) const
{
    return __ArchDistrib__InterfaceMP3_ids[0];
}

const ::std::string&
ArchDistrib::InterfaceMP3::ice_staticId()
{
    return __ArchDistrib__InterfaceMP3_ids[0];
}

::Ice::DispatchStatus
ArchDistrib::InterfaceMP3::___printString(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string s;
    __is->read(s);
    __inS.endReadParams();
    printString(s, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __ArchDistrib__InterfaceMP3_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "printString"
};

}

::Ice::DispatchStatus
ArchDistrib::InterfaceMP3::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__ArchDistrib__InterfaceMP3_all, __ArchDistrib__InterfaceMP3_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ArchDistrib__InterfaceMP3_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___printString(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ArchDistrib::InterfaceMP3::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
ArchDistrib::InterfaceMP3::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
ArchDistrib::__patch(InterfaceMP3Ptr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::ArchDistrib::InterfaceMP3Ptr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::ArchDistrib::InterfaceMP3::ice_staticId(), v);
    }
}
